# Copyright AppsCode Inc. and Contributors
#
# Licensed under the AppsCode Free Trial License 1.0.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/appscode/licenses/raw/1.0.0/AppsCode-Free-Trial-1.0.0.md
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM debian:bullseye

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

RUN set -x \
  && apt-get update \
  && apt-get install -y --no-install-recommends apt-transport-https ca-certificates curl bzip2

RUN set -x                                                                                                                                 \
  && curl -fsSL -o restic.bz2 https://github.com/stashed/restic/releases/download/v{RESTIC_VER}/restic_{RESTIC_VER}_{ARG_OS}_{ARG_ARCH}.bz2 \
  && bzip2 -d restic.bz2                                                                                                                   \
  && chmod 755 restic


FROM {ARG_FROM}

LABEL org.opencontainers.image.source https://github.com/stashed/percona-xtradb

RUN set -e; \
  apt-get update; \
  apt-get install --no-install-recommends --yes \
    apt-transport-https \
    ca-certificates pwgen wget netcat socat \
  && rm -rf /var/lib/apt/lists/*

RUN wget https://repo.percona.com/apt/percona-release_0.1-6.jessie_all.deb \
  && dpkg -i percona-release_0.1-6.jessie_all.deb

RUN apt-get update \
  && apt-get install --no-install-recommends --yes \
  percona-xtrabackup-24 percona-xtradb-cluster-garbd-5.7 percona-server-client-5.7 \
  qpress \
  && rm -rf /var/lib/apt/lists/* \
  && rm percona-release_0.1-6.jessie_all.deb

COPY hack/docker/stash-percona-xtradb/ /

RUN chmod +x /backup.sh \
  && chmod +x /restore.sh

COPY --from=0 /restic /bin/restic
COPY bin/{ARG_OS}_{ARG_ARCH}/{ARG_BIN} /{ARG_BIN}

USER nobody:nobody

ENTRYPOINT ["/{ARG_BIN}"]
