/*
Copyright The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: stash.appscode.dev/percona-xtradb/apis/installer/v1alpha1/generated.proto

package v1alpha1

import (
	fmt "fmt"

	io "io"

	proto "github.com/gogo/protobuf/proto"

	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

func (m *ImageRef) Reset()      { *m = ImageRef{} }
func (*ImageRef) ProtoMessage() {}
func (*ImageRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5ae62a1b196670, []int{0}
}
func (m *ImageRef) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ImageRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ImageRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageRef.Merge(m, src)
}
func (m *ImageRef) XXX_Size() int {
	return m.Size()
}
func (m *ImageRef) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageRef.DiscardUnknown(m)
}

var xxx_messageInfo_ImageRef proto.InternalMessageInfo

func (m *PerconaXtraDBBackup) Reset()      { *m = PerconaXtraDBBackup{} }
func (*PerconaXtraDBBackup) ProtoMessage() {}
func (*PerconaXtraDBBackup) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5ae62a1b196670, []int{1}
}
func (m *PerconaXtraDBBackup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PerconaXtraDBBackup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PerconaXtraDBBackup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PerconaXtraDBBackup.Merge(m, src)
}
func (m *PerconaXtraDBBackup) XXX_Size() int {
	return m.Size()
}
func (m *PerconaXtraDBBackup) XXX_DiscardUnknown() {
	xxx_messageInfo_PerconaXtraDBBackup.DiscardUnknown(m)
}

var xxx_messageInfo_PerconaXtraDBBackup proto.InternalMessageInfo

func (m *PerconaXtraDBRestore) Reset()      { *m = PerconaXtraDBRestore{} }
func (*PerconaXtraDBRestore) ProtoMessage() {}
func (*PerconaXtraDBRestore) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5ae62a1b196670, []int{2}
}
func (m *PerconaXtraDBRestore) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PerconaXtraDBRestore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *PerconaXtraDBRestore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PerconaXtraDBRestore.Merge(m, src)
}
func (m *PerconaXtraDBRestore) XXX_Size() int {
	return m.Size()
}
func (m *PerconaXtraDBRestore) XXX_DiscardUnknown() {
	xxx_messageInfo_PerconaXtraDBRestore.DiscardUnknown(m)
}

var xxx_messageInfo_PerconaXtraDBRestore proto.InternalMessageInfo

func (m *StashPerconaXtraDB) Reset()      { *m = StashPerconaXtraDB{} }
func (*StashPerconaXtraDB) ProtoMessage() {}
func (*StashPerconaXtraDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5ae62a1b196670, []int{3}
}
func (m *StashPerconaXtraDB) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StashPerconaXtraDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *StashPerconaXtraDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StashPerconaXtraDB.Merge(m, src)
}
func (m *StashPerconaXtraDB) XXX_Size() int {
	return m.Size()
}
func (m *StashPerconaXtraDB) XXX_DiscardUnknown() {
	xxx_messageInfo_StashPerconaXtraDB.DiscardUnknown(m)
}

var xxx_messageInfo_StashPerconaXtraDB proto.InternalMessageInfo

func (m *StashPerconaXtraDBList) Reset()      { *m = StashPerconaXtraDBList{} }
func (*StashPerconaXtraDBList) ProtoMessage() {}
func (*StashPerconaXtraDBList) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5ae62a1b196670, []int{4}
}
func (m *StashPerconaXtraDBList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StashPerconaXtraDBList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *StashPerconaXtraDBList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StashPerconaXtraDBList.Merge(m, src)
}
func (m *StashPerconaXtraDBList) XXX_Size() int {
	return m.Size()
}
func (m *StashPerconaXtraDBList) XXX_DiscardUnknown() {
	xxx_messageInfo_StashPerconaXtraDBList.DiscardUnknown(m)
}

var xxx_messageInfo_StashPerconaXtraDBList proto.InternalMessageInfo

func (m *StashPerconaXtraDBSpec) Reset()      { *m = StashPerconaXtraDBSpec{} }
func (*StashPerconaXtraDBSpec) ProtoMessage() {}
func (*StashPerconaXtraDBSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5ae62a1b196670, []int{5}
}
func (m *StashPerconaXtraDBSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StashPerconaXtraDBSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *StashPerconaXtraDBSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StashPerconaXtraDBSpec.Merge(m, src)
}
func (m *StashPerconaXtraDBSpec) XXX_Size() int {
	return m.Size()
}
func (m *StashPerconaXtraDBSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_StashPerconaXtraDBSpec.DiscardUnknown(m)
}

var xxx_messageInfo_StashPerconaXtraDBSpec proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ImageRef)(nil), "stash.appscode.dev.percona_xtradb.apis.installer.v1alpha1.ImageRef")
	proto.RegisterType((*PerconaXtraDBBackup)(nil), "stash.appscode.dev.percona_xtradb.apis.installer.v1alpha1.PerconaXtraDBBackup")
	proto.RegisterType((*PerconaXtraDBRestore)(nil), "stash.appscode.dev.percona_xtradb.apis.installer.v1alpha1.PerconaXtraDBRestore")
	proto.RegisterType((*StashPerconaXtraDB)(nil), "stash.appscode.dev.percona_xtradb.apis.installer.v1alpha1.StashPerconaXtraDB")
	proto.RegisterType((*StashPerconaXtraDBList)(nil), "stash.appscode.dev.percona_xtradb.apis.installer.v1alpha1.StashPerconaXtraDBList")
	proto.RegisterType((*StashPerconaXtraDBSpec)(nil), "stash.appscode.dev.percona_xtradb.apis.installer.v1alpha1.StashPerconaXtraDBSpec")
}

func init() {
	proto.RegisterFile("stash.appscode.dev/percona-xtradb/apis/installer/v1alpha1/generated.proto", fileDescriptor_3c5ae62a1b196670)
}

var fileDescriptor_3c5ae62a1b196670 = []byte{
	// 689 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcf, 0x4f, 0x13, 0x4f,
	0x14, 0xef, 0x7e, 0xdb, 0x42, 0xbf, 0x53, 0x54, 0x18, 0x89, 0xa9, 0x24, 0x2e, 0xa4, 0x27, 0x0e,
	0x32, 0x2b, 0x8d, 0x31, 0x78, 0x64, 0x25, 0x1a, 0x12, 0x01, 0x1d, 0x38, 0x18, 0x63, 0xa2, 0xd3,
	0xed, 0x63, 0xbb, 0xb6, 0xdb, 0x9d, 0xcc, 0x4c, 0x1b, 0xf1, 0xa4, 0x67, 0x2f, 0xfe, 0x59, 0x1c,
	0x39, 0x72, 0x22, 0x52, 0x6f, 0x7a, 0xf7, 0x6c, 0x66, 0x76, 0xfa, 0x73, 0x31, 0x12, 0xe1, 0xb6,
	0xf3, 0xe6, 0xf3, 0xeb, 0xcd, 0xcc, 0x5b, 0xb4, 0x2d, 0x15, 0x93, 0x4d, 0xc2, 0x38, 0x97, 0x41,
	0xd2, 0x00, 0xd2, 0x80, 0x9e, 0xc7, 0x41, 0x04, 0x49, 0x87, 0xad, 0x7d, 0x50, 0x82, 0x35, 0xea,
	0x1e, 0xe3, 0x91, 0xf4, 0xa2, 0x8e, 0x54, 0xac, 0xdd, 0x06, 0xe1, 0xf5, 0xd6, 0x59, 0x9b, 0x37,
	0xd9, 0xba, 0x17, 0x42, 0x07, 0x04, 0x53, 0xd0, 0x20, 0x5c, 0x24, 0x2a, 0xc1, 0x8f, 0xb3, 0x52,
	0xc4, 0x4a, 0xbd, 0x4d, 0xa5, 0x88, 0x96, 0x22, 0x43, 0x29, 0x32, 0x90, 0x5a, 0x5a, 0x0b, 0x23,
	0xd5, 0xec, 0xd6, 0x49, 0x90, 0xc4, 0x5e, 0x98, 0x84, 0x89, 0x67, 0x14, 0xeb, 0xdd, 0x43, 0xb3,
	0x32, 0x0b, 0xf3, 0x95, 0x3a, 0x2d, 0x3d, 0x6c, 0x6d, 0x48, 0x12, 0x25, 0x3a, 0x59, 0xcc, 0x82,
	0x66, 0xd4, 0x01, 0x71, 0xe4, 0xf1, 0x56, 0x98, 0x46, 0x8d, 0x41, 0x31, 0xaf, 0x97, 0xc9, 0xb7,
	0xe4, 0xfd, 0x89, 0x25, 0xba, 0x1d, 0x15, 0xc5, 0x90, 0x21, 0x3c, 0xfa, 0x1b, 0x41, 0x06, 0x4d,
	0x88, 0xd9, 0x34, 0xaf, 0xfa, 0xc5, 0x41, 0xa5, 0xed, 0x98, 0x85, 0x40, 0xe1, 0x10, 0xdf, 0x47,
	0x25, 0x01, 0x61, 0x24, 0x95, 0x38, 0xaa, 0x38, 0x2b, 0xce, 0xea, 0xff, 0xfe, 0xfc, 0xf1, 0xd9,
	0x72, 0xae, 0x7f, 0xb6, 0x5c, 0xa2, 0xb6, 0x4e, 0x87, 0x08, 0x5c, 0x43, 0x48, 0x00, 0x4f, 0x64,
	0xa4, 0x12, 0x71, 0x54, 0xf9, 0xcf, 0xe0, 0xb1, 0xc5, 0x23, 0x3a, 0xdc, 0xa1, 0x63, 0x28, 0x7c,
	0x0f, 0xe5, 0x15, 0x0b, 0x2b, 0x79, 0x03, 0x2e, 0x5b, 0x70, 0xfe, 0x80, 0x85, 0x54, 0xd7, 0xab,
	0x2d, 0x74, 0xfb, 0x45, 0x7a, 0x0b, 0xaf, 0x94, 0x60, 0x5b, 0xbe, 0xcf, 0x82, 0x56, 0x97, 0xe3,
	0x15, 0x54, 0x60, 0x22, 0x94, 0x36, 0xd3, 0x9c, 0xa5, 0x15, 0x36, 0x45, 0x28, 0xa9, 0xd9, 0xd1,
	0x59, 0x64, 0x12, 0x30, 0x45, 0x41, 0xd9, 0x2c, 0xc5, 0x51, 0x96, 0xfd, 0xe1, 0x0e, 0x1d, 0x43,
	0x55, 0x3f, 0x3b, 0x68, 0x71, 0xc2, 0x8d, 0x82, 0x54, 0x89, 0x80, 0x4b, 0xd8, 0x3d, 0x43, 0x0b,
	0x8a, 0x89, 0x10, 0xd4, 0x26, 0xe7, 0x14, 0x78, 0x3b, 0x0a, 0x98, 0xb4, 0xae, 0x77, 0x2d, 0x7c,
	0xe1, 0x60, 0x1a, 0x40, 0xb3, 0x9c, 0xea, 0x4f, 0x07, 0xe1, 0x7d, 0xfd, 0x14, 0x27, 0x82, 0xe0,
	0x77, 0xa8, 0xa4, 0x5f, 0x46, 0x83, 0x29, 0x66, 0x52, 0x94, 0x6b, 0x0f, 0x48, 0x7a, 0xc1, 0x64,
	0xfc, 0x82, 0x09, 0x6f, 0x85, 0xe9, 0x3b, 0xd5, 0x68, 0xd2, 0x5b, 0x27, 0x7b, 0xf5, 0xf7, 0x10,
	0xa8, 0x1d, 0x50, 0x6c, 0xd4, 0xfe, 0xa8, 0x46, 0x87, 0xaa, 0x58, 0xa2, 0x82, 0xe4, 0x10, 0x98,
	0xd0, 0xe5, 0xda, 0x4b, 0xf2, 0xcf, 0xf3, 0x40, 0xb2, 0xf1, 0xf7, 0x39, 0x04, 0xa3, 0x63, 0xd3,
	0x2b, 0x6a, 0xcc, 0xaa, 0x3f, 0x1c, 0x74, 0x27, 0x0b, 0x7f, 0x1e, 0x49, 0x85, 0xdf, 0x64, 0x3a,
	0x26, 0x97, 0xeb, 0x58, 0xb3, 0x4d, 0xbf, 0xc3, 0xa7, 0x3a, 0xa8, 0x8c, 0x75, 0x2b, 0x50, 0x31,
	0x52, 0x10, 0xeb, 0x3b, 0xca, 0xaf, 0x96, 0x6b, 0x3b, 0xd7, 0xda, 0xae, 0x7f, 0xc3, 0x3a, 0x17,
	0xb7, 0xb5, 0x07, 0x4d, 0xad, 0xaa, 0xbf, 0xf2, 0x17, 0x35, 0xab, 0x4f, 0x03, 0x6f, 0xa0, 0xb9,
	0x0e, 0x8b, 0x61, 0xaf, 0x07, 0x42, 0x44, 0x0d, 0xb0, 0x0f, 0x6d, 0xd1, 0xca, 0xcc, 0xed, 0x8e,
	0xed, 0xd1, 0x09, 0x24, 0xde, 0x42, 0xf3, 0x87, 0xdd, 0x76, 0x7b, 0x82, 0x9d, 0x4e, 0x5e, 0xc5,
	0xb2, 0xe7, 0x9f, 0x4e, 0xed, 0xd3, 0x0c, 0x03, 0x37, 0x51, 0x31, 0xd2, 0x33, 0x6f, 0xe6, 0xb0,
	0x5c, 0x7b, 0x72, 0x85, 0xe3, 0x18, 0xfc, 0x3b, 0xc6, 0x0e, 0xc1, 0x54, 0x52, 0x03, 0xdc, 0x43,
	0x33, 0x75, 0x33, 0xc3, 0x95, 0x82, 0xb1, 0xda, 0xbd, 0x82, 0xd5, 0x05, 0x7f, 0x06, 0xff, 0xa6,
	0x75, 0x9d, 0x49, 0xd7, 0xd4, 0xba, 0xe1, 0x8f, 0x68, 0x56, 0xa4, 0xd3, 0x5c, 0x29, 0x1a, 0xe3,
	0xbd, 0xeb, 0x32, 0xb6, 0x3f, 0x09, 0xff, 0x96, 0x75, 0x9e, 0xb5, 0x05, 0x3a, 0x30, 0xf4, 0xc9,
	0xf1, 0xb9, 0x9b, 0x3b, 0x39, 0x77, 0x73, 0xa7, 0xe7, 0x6e, 0xee, 0x53, 0xdf, 0x75, 0x8e, 0xfb,
	0xae, 0x73, 0xd2, 0x77, 0x9d, 0xd3, 0xbe, 0xeb, 0x7c, 0xeb, 0xbb, 0xce, 0xd7, 0xef, 0x6e, 0xee,
	0x75, 0x69, 0x20, 0xff, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x66, 0xf0, 0x2a, 0x78, 0xd7, 0x06, 0x00,
	0x00,
}

func (m *ImageRef) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ImageRef) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ImageRef) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.Tag)
	copy(dAtA[i:], m.Tag)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Tag)))
	i--
	dAtA[i] = 0x1a
	i -= len(m.Repository)
	copy(dAtA[i:], m.Repository)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Repository)))
	i--
	dAtA[i] = 0x12
	i -= len(m.Registry)
	copy(dAtA[i:], m.Registry)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Registry)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PerconaXtraDBBackup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PerconaXtraDBBackup) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PerconaXtraDBBackup) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i = encodeVarintGenerated(dAtA, i, uint64(m.SocatRetry))
	i--
	dAtA[i] = 0x10
	i -= len(m.Args)
	copy(dAtA[i:], m.Args)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Args)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PerconaXtraDBRestore) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PerconaXtraDBRestore) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PerconaXtraDBRestore) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i = encodeVarintGenerated(dAtA, i, uint64(m.TargetAppReplicas))
	i--
	dAtA[i] = 0x10
	i -= len(m.Args)
	copy(dAtA[i:], m.Args)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Args)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *StashPerconaXtraDB) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StashPerconaXtraDB) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StashPerconaXtraDB) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *StashPerconaXtraDBList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StashPerconaXtraDBList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StashPerconaXtraDBList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *StashPerconaXtraDBSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StashPerconaXtraDBSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StashPerconaXtraDBSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Restore.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.Backup.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.Image.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	i -= len(m.FullnameOverride)
	copy(dAtA[i:], m.FullnameOverride)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.FullnameOverride)))
	i--
	dAtA[i] = 0x12
	i -= len(m.NameOverride)
	copy(dAtA[i:], m.NameOverride)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.NameOverride)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerated(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ImageRef) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Registry)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Repository)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Tag)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *PerconaXtraDBBackup) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Args)
	n += 1 + l + sovGenerated(uint64(l))
	n += 1 + sovGenerated(uint64(m.SocatRetry))
	return n
}

func (m *PerconaXtraDBRestore) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Args)
	n += 1 + l + sovGenerated(uint64(l))
	n += 1 + sovGenerated(uint64(m.TargetAppReplicas))
	return n
}

func (m *StashPerconaXtraDB) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *StashPerconaXtraDBList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *StashPerconaXtraDBSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NameOverride)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.FullnameOverride)
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Image.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Backup.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Restore.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func sovGenerated(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *ImageRef) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ImageRef{`,
		`Registry:` + fmt.Sprintf("%v", this.Registry) + `,`,
		`Repository:` + fmt.Sprintf("%v", this.Repository) + `,`,
		`Tag:` + fmt.Sprintf("%v", this.Tag) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PerconaXtraDBBackup) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PerconaXtraDBBackup{`,
		`Args:` + fmt.Sprintf("%v", this.Args) + `,`,
		`SocatRetry:` + fmt.Sprintf("%v", this.SocatRetry) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PerconaXtraDBRestore) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PerconaXtraDBRestore{`,
		`Args:` + fmt.Sprintf("%v", this.Args) + `,`,
		`TargetAppReplicas:` + fmt.Sprintf("%v", this.TargetAppReplicas) + `,`,
		`}`,
	}, "")
	return s
}
func (this *StashPerconaXtraDB) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StashPerconaXtraDB{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "StashPerconaXtraDBSpec", "StashPerconaXtraDBSpec", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *StashPerconaXtraDBList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]StashPerconaXtraDB{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "StashPerconaXtraDB", "StashPerconaXtraDB", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&StashPerconaXtraDBList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *StashPerconaXtraDBSpec) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&StashPerconaXtraDBSpec{`,
		`NameOverride:` + fmt.Sprintf("%v", this.NameOverride) + `,`,
		`FullnameOverride:` + fmt.Sprintf("%v", this.FullnameOverride) + `,`,
		`Image:` + strings.Replace(strings.Replace(this.Image.String(), "ImageRef", "ImageRef", 1), `&`, ``, 1) + `,`,
		`Backup:` + strings.Replace(strings.Replace(this.Backup.String(), "PerconaXtraDBBackup", "PerconaXtraDBBackup", 1), `&`, ``, 1) + `,`,
		`Restore:` + strings.Replace(strings.Replace(this.Restore.String(), "PerconaXtraDBRestore", "PerconaXtraDBRestore", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *ImageRef) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ImageRef: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ImageRef: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Registry", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Registry = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Repository", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Repository = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tag = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PerconaXtraDBBackup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PerconaXtraDBBackup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PerconaXtraDBBackup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Args", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Args = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SocatRetry", wireType)
			}
			m.SocatRetry = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SocatRetry |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PerconaXtraDBRestore) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PerconaXtraDBRestore: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PerconaXtraDBRestore: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Args", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Args = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetAppReplicas", wireType)
			}
			m.TargetAppReplicas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetAppReplicas |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StashPerconaXtraDB) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StashPerconaXtraDB: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StashPerconaXtraDB: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StashPerconaXtraDBList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StashPerconaXtraDBList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StashPerconaXtraDBList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, StashPerconaXtraDB{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StashPerconaXtraDBSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StashPerconaXtraDBSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StashPerconaXtraDBSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NameOverride", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NameOverride = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FullnameOverride", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FullnameOverride = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Image", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Image.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Backup", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Backup.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Restore", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Restore.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipGenerated(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthGenerated
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthGenerated = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated   = fmt.Errorf("proto: integer overflow")
)
